### ISSUE TITLE
BUG: Duplicates within the same file upload 

### ISSUE THREAD

**Issue by clukhei** [TechLadies/reach-backend#31]
@thchia esp needs to see this :D

Please refer to route /upload 

Consider this scenario : 

1) Salutations that exist on database currently: "Mr" and "Mrs" 
2) A new file uploaded with more than one donors that has salutation "Madame"  ("Madame" does not exist on salutation table) 
3) After upload is complete the db.Salutation table is expected to have: 

**id      description**
1        Mr
2        Mrs
3        Madame

However, this is what is happening : 
![image](https://user-images.githubusercontent.com/55618945/75052177-21017900-550a-11ea-9a22-8150404b43b9.png)
The same Madame has more than 1 id ! 
This only happens when the salutation does not exist in the database. If I subsequent make another file upload with "Madame" again (now "Madame" already exist in db) , duplication will not happen 

This problem happens for those fields that were cached 
![image](https://user-images.githubusercontent.com/55618945/75052364-73db3080-550a-11ea-99b5-3384ca285634.png)
i.e. (salutation, id type, payment type, project) 

While debugging , I console.log(description) and console.log(found) 
![image](https://user-images.githubusercontent.com/55618945/75052705-fbc13a80-550a-11ea-9703-a3c232db7dd1.png)

and this is what it looks like :

![image](https://user-images.githubusercontent.com/55618945/75052549-c1579d80-550a-11ea-96fc-1008ea12aab0.png)

After the first entry of donor with "Madame" is inserted into the database, the salutationId for "Madame" is not reflected in the cache when the second entry of donor is processed. 

I think it has something to do with the asynchronous events, but there are too many promises embedded in promises , I cant debug this :0 

--> Also, do we allow the user to upload salutations/id type/Type of payment without restrictions? Should we hardcode all the possible salutations/id type/ type of payment in the table and do a validation on the incoming salutation/id type/type of payment instead . This will solve the problem as duplications only happens when something does not exist in the db but.....

--> Project model still needs the debugging!

**Comment by thchia** [comment]
This is a great issue description. I’ll take a look.

**Comment by thchia** [comment]
>--> Also, do we allow the user to upload salutations/id type/Type of payment without restrictions? Should we hardcode all the possible salutations/id type/ type of payment in the table and do a validation on the incoming salutation/id type/type of payment instead . This will solve the problem as duplications only happens when something does not exist in the db but.....

We can discuss this. My concern is that if we define it up front, and one day the user attempts to upload a donation with a new type of salutation, how are they going to add that to the Salutation table? If you think it's worth going this way, let's create a new issue.

>--> Project model still needs the debugging!

I have no idea what you mean here lol. Is there some known issue?
