### ISSUE TITLE
Donation Amount dataType in postgres needs discussion 

### ISSUE THREAD

**Issue by clukhei** [TechLadies/reach-backend#38]
Hi all,

I dont know how important is this issue, but just raise it up here. 
Currently donationAmount is defined as dataTypes.NUMERIC . It returns as a string in response data as sequelize does not parse it to a value unlike dataTypes.INTEGER 

(link for reference ) https://github.com/sequelize/sequelize/blob/2874c54915b2594225e939809ca9f8200b94f454/lib/dialects/postgres/data-types.js#L102

My understanding is that javascript has precision issues for decimal values https://stackoverflow.com/questions/2876536/precise-financial-calculation-in-javascript-what-are-the-gotchas

Im not sure how's the donations in REACH like, but since its money , its likely that people donate to the decimal value? Please refer to 
![image](https://user-images.githubusercontent.com/55618945/76487133-699eb900-645c-11ea-9207-00ee7c7175ed.png)

Currently, I did a quickfix to change string format to value using parseFloat() . Is this a good enough fix ? 

If not, either we use a financial library to manage the donationAmount or we count the donation amount down to cents. 

Lets discuss this!

**Comment by thchia** [comment]
You are right that there are gotchas with arithmetic in JavaScript.

If I understand you correctly, you are concerned about the accuracy of the sum function?

**Comment by clukhei** [comment]
Yeap, thats right . Concern with accuracy of sum function when I convert string to values in parseFloat

**Comment by thchia** [comment]
Before parseFloat, what was sequelize treating it as?

FYI if it was treating it as a string, we would have got wildly incorrect results because

```js
“1” + “1” === “11”
```

**Comment by clukhei** [comment]
You are right. It was treating it as string and concatenated donation amt.
That's why I needed to change it to value

**Comment by shangong** [comment]
Seeing that the discussion has gone cold, 
1. I'd like to add that donations must be whole numbers and not spare change and that might lead to problems.
2. I'm wondering what has been done? @clukhei

**Comment by clukhei** [comment]
Not much is done 

Currently data type for donationAmount is still NUMERIC. It is returned as a string in response. I'm using parseFloat() as a temporary measure to convert the string to values in order to sum. So the arithmetic problem still persist. 

Thinking of using a financial library to handle this.

**Comment by clukhei** [comment]
I will go with decimal.js library for arithmetic calculations of donation amounts @shangong
