### ISSUE TITLE
reset password flow discussion

### ISSUE THREAD

**Issue by clukhei** [TechLadies/reach-backend#48]
Hi REACH team , 

this is my draft idea on how password reset flow will be like. Appreciate your review and comments @shangong @thchia @SheldonCheng @psjoshi20 @gnelak 

On FE, 
>User clicks forget password
>enters email address and submits 

On BE, 
>submission calls a db query to verify if email address exist
if email address exist : 
>1) generate cryto-randomByte token (time limit applies) 
>2) insert token to Users table (need to create a new column in User Table to store this token) 
>3) server sends email with password reset link and token using nodemailer library 
 (heroku has this as an add on service, otherwise for production, nodemailer allows to create and send from a test account) 

On FE, 
> Link directs user to reset password page 
> user submits 2 password to BE 

On BE, 
> if 2 passwords are identical and a req.body token exist, update password where token in User table is the same 
> on db the token may have expire( or deleted after expired), in this case the update will not happen 

references: 
token: use jwt or crypto.randomByte ? :
https://security.stackexchange.com/questions/213975/how-to-properly-create-a-password-reset-token

reset password flow: 
https://www.codementor.io/@olatundegaruba/password-reset-using-jwt-ag2pmlck0

nodemailer, and testing account:
https://nodemailer.com/smtp/testing/

**Comment by thchia** [comment]
This is the right high level idea.
