### ISSUE TITLE
Non-unique donations not deduped in upload response

### ISSUE THREAD

**Issue by thchia** [TechLadies/reach-backend#55]
If 2 donations from the same donor with the same receipt ID are upload, the success screen shows that donor as having made 2 donations. Since the receipt ID is the same, it should only be counted as one.

Offending line (it does not dedupe based on receipt number):

https://github.com/TechLadies/reach-backend/blob/81e688fd60c564463c0270cf459c3b6a79168aa1/src/routes/donations.js#L331

**Comment by clukhei** [comment]
I was wondering what happens if two different donors use the same receipt no.

**Comment by thchia** [comment]
According to the code, I believe what will happen is:
- the DB will still have one donation, tagged to whoever's name came last in the upload (it will overwrite the first one)
- The success response will show Donor 1 has having made 1 donation, and Donor 2 as having made 1 donation also (because we group the donations by donor first, so the 2 donations will not appear "together" after that)

**Comment by thchia** [comment]
Fixed in #58
