### ISSUE TITLE
Endpoint Authentication

### ISSUE THREAD

**Issue by clukhei** [TechLadies/reach-backend#59]
Hi , Im guessing that backend also requires authentication... 

What are the endpoints that require authentication? Is it only for those that returns sensitive information like donors contact and personal info? Or every endpoint needs authentication (except reset-ps and login)

I think I can do this :) 
Also quite a few dummy endpoints created earlier in during dev. Shall I clean them up? 

@thchia

**Comment by thchia** [comment]
I think every endpoint should have it except login and reset password.

Instead of adding it individually to each endpoint, you can consider adding it to the main routes page (where you have `app.use(‘/donors’, ...)`).
