### ISSUE TITLE
Accumulation of Sequelize unhandle rejection error causes db to be stucked

### ISSUE THREAD

**Issue by clukhei** [TechLadies/reach-backend#62]
Error description: 
Upload failed with timeout error 

Heroku logs : 
<img width="954" alt="heroku logs query stucked at transaction" src="https://user-images.githubusercontent.com/55618945/84681783-3d1ca080-af67-11ea-825c-6ce359e424e3.PNG">

After some googling, I found that there are some stucked transactions in Heroku Postgres:

`SELECT pid , query from pg_stat_activity WHERE state != 'idle' ORDER BY xact_start;`

<img width="956" alt="four idle transactions leads to a stucked DB!" src="https://user-images.githubusercontent.com/55618945/84681739-2aa26700-af67-11ea-98d7-b8bd45337cdb.PNG">

After clearing out the idle transactions , using following command 
` select pg_terminate_backend(17027);`

I was able to upload files as per normal. 

I replicated this error by performing four failed uploads using a defect file (i.e. remove source value from some rows in csv file) 
this  returns sequelize unhandled rejection error: 
![image](https://user-images.githubusercontent.com/55618945/84682205-e4013c80-af67-11ea-93ab-bf5b8c6b915e.png)

After doing this for four times , I was then unable to upload a normal csv file that would have worked well in normal situation. 

Clearing the idle transactions, solved the problem again. 

Question: 
Seems like the error is caused by unhandled rejection error..
What is the right way to handle the database rejection error ?

**Comment by thchia** [comment]
If you are able to reproduce locally, can you try while running the `fix/uncaught-insert` branch? I'm not 100% sure if that is the issue.
